SangesAntonio/deliveboo

app/Http/Controllers/Admin/ProductController.php

ho creato le basi per le crud dei prodotti

added product crud

---

app/Http/Controllers/Admin/OrderController.php

Adds Orders Controller Validation (Store & Update)

Adds Orders Validation

---

app/Http/Controllers/Admin/OrderController.php

Adds Regex to Orders Email Validation

Adds Regex to Orders Email Validation

---

public/css/app.css
public/js/app.js
resources/sass/_navbar.scss
resources/views/admin/home.blade.php
resources/views/guest/home.blade.php
resources/views/includes/navbar.blade.php

modified home links

---

public/css/app.css
resources/views/auth/register.blade.php

modified the register form for the restaurant registar form

restaurant form added

---

app/Http/Controllers/Admin/ProductController.php
app/Http/Controllers/Admin/UserController.php
public/css/app.css
public/js/app.js
resources/sass/_form.scss
resources/sass/app.scss
resources/views/admin/products/create.blade.php
resources/views/includes/products/form.blade.php
resources/views/layouts/app.blade.php

creato form incluso in product create

added form in product create

---

public/js/app.js
resources/views/admin/products/index.blade.php
resources/views/admin/products/show.blade.php

added the show feature on the single product (maybe we have to add the allergens of the product)

added product show

---

resources/views/admin/products/index.blade.php

Aggiunti i bottoni nelle card dei prodotti e le collega alle singole show

Adds buttons to product cards

---

app/Http/Controllers/Admin/ProductController.php
public/js/app.js
resources/views/includes/products/form.blade.php

aggiunto validazione form create e edit prodotti

added validation front side

---

public/css/modal.css
public/js/app.js
public/js/delete-form.js
public/mix-manifest.json
resources/js/delete-form.js
resources/views/admin/products/index.blade.php
resources/views/layouts/app.blade.php
webpack.mix.js

Aggiunto l'alert per il delete-form

Adds delete-form alert

---

app/Http/Controllers/Admin/UserController.php
app/Http/Controllers/Auth/RegisterController.php
app/User.php
database/migrations/2014_10_12_000000_create_users_table.php
resources/views/auth/register.blade.php
routes/api.php

fixato il form di registrazione, aggiunto il campo immagine, protetto la tabella users e validato correttamente in registercontroller

fixed register form and validate

---

resources/views/admin/products/index.blade.php
resources/views/includes/products/form.blade.php

Aggiunto il tasto "Crea Prodotto" + Migliora layout grafico

Fixes products index layout + adds create product

---

resources/views/includes/products/form.blade.php

fixed price form

---

database/migrations/2022_04_26_084257_create_orders_table.php
database/migrations/2022_04_26_134309_update_order_product_table.php
database/seeds/OrderSeeder.php
database/seeds/ProductSeeder.php
database/seeds/UserSeeder.php

aggiunto seeder ordini e seeder nella tabella ordini_prodotti con faker

added order and order_product tables seeder

---

app/Http/Controllers/Admin/ProductController.php
app/Http/Controllers/Auth/RegisterController.php
resources/views/admin/users/index.blade.php
resources/views/auth/register.blade.php
resources/views/includes/navbar.blade.php
resources/views/includes/products/form.blade.php

aggiunto le immagini alo storage path in public, fixato problema di registrazione + problema add prodotti

fix register form+add products error+storage img

---

app/Http/Controllers/Admin/OrderController.php
app/Providers/AppServiceProvider.php
public/js/app.js
public/js/delete-form.js
resources/views/admin/orders/index.blade.php

modificato index degli ordini e aggiunto bottone per la show. Aggiunto paginazione provvisoria

fixed orders index

---

app/Http/Controllers/Admin/OrderController.php
resources/views/admin/orders/index.blade.php

fixato paginazione degli ordini

added pagination

---

resources/views/admin/orders/show.blade.php

modificato leggermente la show degli ordini

style order show

---

public/css/app.css
public/js/app.js
resources/sass/_orders.scss
resources/sass/app.scss
resources/views/admin/orders/index.blade.php

edited layout of pagination bar

changed pagination bar

---

public/css/app.css
resources/sass/_orders.scss
resources/views/admin/orders/show.blade.php

added style to product show , need to be finish

edited product show

---

public/js/app.js
public/js/delete-form.js
resources/views/admin/orders/index.blade.php

cambiato lo stile della tabella ... inserito il rounded per un effetto smooth

changed table mod 1

---

public/css/app.css
resources/sass/_orders.scss
resources/views/admin/orders/index.blade.php

changed the bg-color of the order list table

changed order list table style

---

app/Http/Controllers/Admin/ProductController.php
app/Http/Controllers/Admin/UserController.php
public/js/app.js
public/js/delete-form.js
resources/views/admin/users/edit.blade.php
resources/views/admin/users/index.blade.php

created edit form for the restaurant

---

app/Http/Controllers/Admin/OrderController.php
resources/views/admin/orders/index.blade.php

aggiunto modale alla index degli ordini

added modal to order index

---

public/css/app.css
resources/sass/_usercard.scss
resources/views/admin/users/index.blade.php

edited position & dimension "edit" button

edited button

---

resources/views/admin/orders/index.blade.php

fixed modale

---

public/css/app.css
public/css/navbar2.css
public/js/app.js
public/js/delete-form.js
resources/sass/_navbar.scss
resources/sass/_navbar2.scss
resources/sass/_utils.scss
resources/sass/app.scss
resources/views/admin/users/index.blade.php
resources/views/includes/navbar.blade.php
resources/views/includes/navbar2.blade.php
resources/views/layouts/app.blade.php

Enanches navbar (responsive)

---

resources/views/admin/products/index.blade.php

agiunto modale per eliminazione dei prodotti

added modal delete in products index

---

app/Http/Controllers/Admin/ProductController.php
app/Http/Controllers/Admin/UserController.php
public/css/app.css
public/js/app.js
routes/web.php

I ristoratori possono editare solamente il loro ristorante, se provano a scrivere dalla riga di comando l'id di un altro ristorante si finisce in 404. Stessa cosa per i prodotti che non sono stati creati da loro non possono accedere al database

users cant edit other users, or products

---

public/js/components/App.vue
public/js/front.js
resources/js/routes.js

routes added

---

resources/js/components/HomePage.vue
resources/js/components/PaymentCheckout.vue
resources/js/components/ProductListPage.vue
resources/js/components/RestaurantListPage.vue
resources/js/components/SingleProductPage.vue
resources/js/components/SingleRestaurantPage.vue

added the defaults vue components of all the  vue routes

Added Vue Components

---

app/Http/Controllers/Admin/ProductController.php
app/Http/Controllers/Trash/ProductController.php
app/Models/Product.php
database/migrations/2022_05_03_093012_add_soft_delete_on_products_table.php
public/css/app.css
public/js/app.js
public/js/delete-form.js
resources/views/admin/products/trash/index.blade.php
routes/web.php

Aggiunto sistema di softdelete con "vedi cestino", ecc.

Adds softdelete

---

.gitignore
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2022_04_26_083653_create_products_table.php
database/migrations/2022_04_26_084149_create_categories_table.php
database/seeds/CategorySeeder.php
database/seeds/ProductSeeder.php
database/seeds/UserSeeder.php
public/mix-manifest.json
public/storage/.gitignore

cambiato il campo descrizione dei prodotti in "ingredienti", aggiunto il campo phone number in user.
Seed con dati reali per categorie e user

changed migration, seed real categories and users

---

public/css/app.css
resources/js/components/Navbar.vue
resources/js/front.js
resources/sass/_utils.scss
resources/sass/_variables.scss

Adds more navbar details

---

app/Http/Controllers/Api/UserController.php
resources/js/components/App.vue
resources/js/components/ModalCart.vue
resources/js/components/restaurants/SingleRestaurantPage.vue
resources/js/routes.js
resources/sass/_cartmodal.scss
resources/sass/app.scss
routes/api.php

aggiunto api per singoli ristoranti

added single restaurant api

---

public/css/app.css
public/js/app.js
public/js/delete-form.js
public/js/imag-preview.js
public/js/index.js
public/js/main.js
public/js/plugin.js
public/mix-manifest.json
resources/js/components/products/ProductCard.vue
resources/js/components/restaurants/Card.vue
resources/js/components/restaurants/RestaurantListPage.vue
resources/js/components/restaurants/SingleRestaurantPage.vue
resources/js/js_payment/index.js
resources/js/js_payment/main.js

aggiunto pagina ristorante singolo e card dei prodotti

added single restauran page

---

resources/js/components/App.vue
resources/js/components/ModalCart.vue
resources/js/components/products/ProductCard.vue
resources/js/components/restaurants/SingleRestaurantPage.vue

added cart quantity

---

public/js/index.js
public/js/main.js
public/js/plugin.js
resources/js/components/restaurants/Card.vue
resources/js/components/restaurants/RestaurantListPage.vue
resources/views/guest/home.blade.php

restyled the restaurant list page and all restaurant cards

styling restaurant list page

---

public/mix-manifest.json
resources/js/components/Navbar.vue
resources/js/components/restaurants/RestaurantListPage.vue

Fixes small details

---

resources/js/components/ModalCart.vue
resources/js/components/products/ProductCard.vue
resources/js/components/restaurants/CardDetail.vue
resources/js/components/restaurants/SingleRestaurantPage.vue

corretto vari problemi mentali del carrello

issue cart quantity

---

resources/js/components/ModalCart.vue
resources/js/components/products/ProductCard.vue
resources/js/components/restaurants/CardDetail.vue

aggiunto immagini nelle card dei prodotti del ristornare e una pill per il totale dei prodotti nel carrello

added images product and cart total pill

---

resources/js/components/pages/HomePage.vue

added dynamic categories cards with an axios call

axios category call added

---

resources/js/components/App.vue
resources/js/components/ModalCart.vue
resources/js/components/restaurants/CardDetail.vue
resources/js/components/restaurants/SingleRestaurantPage.vue

fixato il counter del carrello

fixed cart counter

---

resources/js/components/OrderForm.vue
resources/js/components/OrderSummary.vue
resources/js/components/summary/DeliverySummary.vue
resources/js/components/summary/ProductSummary.vue
resources/js/routes.js

added order summary component and the form to take the delivery informations of the client

added order summary and deliveryform

---

resources/js/components/App.vue
resources/js/components/Footer.vue

added the footer nou doesn't work

footer (no working) added

---

resources/js/components/ModalCart.vue
resources/js/components/OrderForm.vue
resources/js/components/PaymentCheckout.vue
resources/js/components/payment/DemoPayment.vue

aggiunto nella modale del carrello, il form per completare l'ordine e i bottoni per andare al pagamento o tornare indietro al carrello

added in modal cart, form order and payments

---

resources/js/components/Footer.vue

changed main colors and added some responsive options

fixed footer

---

package-lock.json
package.json
resources/js/components/ModalCart.vue
resources/js/components/OrderForm.vue
resources/js/components/OrderSummary.vue
resources/js/components/PaymentCheckout.vue
resources/js/components/restaurants/CardDetail.vue
resources/js/components/summary/DeliverySummary.vue
resources/js/routes.js

aggiunto validazione form dell'ordine e passato le informazioni del contatto nel pagamento

added validation form and payments info

---

app/Http/Controllers/Api/UserController.php
resources/js/components/Pagination.vue
resources/js/components/restaurants/RestaurantListPage.vue

Adds Pagination to Restaurant List Page

Adds Pagination to Restaurant List Page

---

resources/js/components/products/ProductCard.vue
resources/js/components/restaurants/SingleRestaurantPage.vue

added the style on the product cards

product style added

---

resources/js/components/restaurants/SingleRestaurantPage.vue

fixed product card issue (broken continium container>row>col)

fixed product card issue

---

resources/js/components/OrderForm.vue
resources/views/admin/orders/index.blade.php

added lastname validation
